/** Unique identifier for every model element. Generated by `model/ids.ts`. */
export type Id = string;

/** Chen cardinality. `M` and `N` both mean "many"; the letter is a style choice. */
export type Cardinality = '1' | 'N' | 'M';

/** Whether every instance of an entity must take part in a relationship. */
export type Participation = 'partial' | 'total';

/** What an attribute can hang off. `attribute` means a part of a composite. */
export type OwnerKind = 'entity' | 'relationship' | 'attribute';

/** How an attribute's ellipse is drawn (SPEC.md §6). */
export type AttributeShape = 'simple' | 'composite' | 'multivalued' | 'derived';

/** How an attribute's name is underlined (SPEC.md §6). */
export type AttributeIdentifier = 'none' | 'key' | 'partial';

export type EntityKind = 'regular' | 'weak';

export type RelationshipKind = 'regular' | 'identifying';

/** Discriminator for "what sort of thing is this id?" lookups. */
export type ElementKind = 'entity' | 'relationship' | 'attribute';

/** Hex colour, e.g. `#2563eb`. Validated by the schema. */
export type Color = string;

export interface Entity {
  id: Id;
  name: string;
  kind: EntityKind;
}

export interface Attribute {
  id: Id;
  /** Id of the owning entity, relationship, or composite attribute. */
  ownerId: Id;
  ownerKind: OwnerKind;
  name: string;
  shape: AttributeShape;
  /**
   * The ER identifier, drawn as an underline. Belongs to entity attributes
   * only; the checks in SPEC.md §7 flag it anywhere else rather than the file
   * being rejected.
   */
  identifier: AttributeIdentifier;
  /**
   * Relational, not ER, and independent of `identifier`: an attribute can be a
   * primary key and a foreign key at once. Drawn as a cable marker.
   */
  foreignKey: boolean;
}

export interface RelationshipEnd {
  entityId: Id;
  /**
   * Counts the entity at THIS end, look-across style (SPEC.md §5):
   * in `PUBLISHER -1- published_by -N- BOOK` the `N` sits on the BOOK end and
   * means "one publisher has many books".
   * `null` means the student has not decided yet.
   */
  cardinality: Cardinality | null;
  participation: Participation;
  /** Shown on self-relationship ends; `null` elsewhere. */
  role: string | null;
}

export interface Relationship {
  id: Id;
  name: string;
  kind: RelationshipKind;
  /** At least two. The same entity may appear more than once (self-relationship). */
  ends: RelationshipEnd[];
}

/** The semantic model. Correctness depends on this alone, never on layout or colour. */
export interface ErModel {
  entities: Entity[];
  attributes: Attribute[];
  relationships: Relationship[];
}

export interface Position {
  x: number;
  y: number;
}

export interface Layout {
  /**
   * Entities and relationships are absolute canvas coordinates; attributes are
   * offsets relative to their owner (SPEC.md §4).
   */
  positions: Record<Id, Position>;
}

/** Default colour per component kind. */
export interface ComponentTheme {
  entity: Color;
  relationship: Color;
  attribute: Color;
}

/**
 * Everything about how the diagram looks that is not position. Kept out of
 * `ErModel` so that recolouring a diagram cannot change a single check result
 * (SPEC.md §1, product rule 2).
 */
export interface Presentation {
  theme: ComponentTheme;
  /** Per-element overrides, keyed by element id. Beats the theme. */
  colors: Record<Id, Color>;
}

export interface ErDocument {
  version: 2;
  title: string;
  model: ErModel;
  layout: Layout;
  presentation: Presentation;
  /** Keys produced by `model/dismissals.ts`. */
  dismissedHints: string[];
}
