/** Unique identifier for every model element. Generated by `model/ids.ts`. */
export type Id = string;

/** Chen cardinality. `M` and `N` both mean "many"; the letter is a style choice. */
export type Cardinality = '1' | 'N' | 'M';

/** What an attribute can hang off. Widened in phase 2 only if new owners appear. */
export type OwnerKind = 'entity' | 'relationship';

/** Attribute flavour. Phase 2 adds `partial-key`, `multivalued`, `derived`, `composite`. */
export type AttributeKind = 'simple' | 'key';

/** Discriminator for "what sort of thing is this id?" lookups. */
export type ElementKind = 'entity' | 'relationship' | 'attribute';

/** Index into `Relationship.ends`. Phase 2 widens `ends` to n-ary. */
export type EndIndex = 0 | 1;

export interface Entity {
  id: Id;
  name: string;
}

export interface Attribute {
  id: Id;
  /** Id of the owning entity or relationship. */
  ownerId: Id;
  ownerKind: OwnerKind;
  name: string;
  kind: AttributeKind;
}

export interface RelationshipEnd {
  entityId: Id;
  /**
   * Counts the entity at THIS end, look-across style (SPEC.md §5):
   * in `PUBLISHER -1- published_by -N- BOOK` the `N` sits on the BOOK end and
   * means "one publisher has many books".
   * `null` means the student has not decided yet.
   */
  cardinality: Cardinality | null;
}

export interface Relationship {
  id: Id;
  name: string;
  /** Widened to `RelationshipEnd[]` in phase 2 for ternary relationships. */
  ends: [RelationshipEnd, RelationshipEnd];
}

/** The semantic model. Correctness depends on this alone, never on `Layout`. */
export interface ErModel {
  entities: Entity[];
  attributes: Attribute[];
  relationships: Relationship[];
}

export interface Position {
  x: number;
  y: number;
}

export interface Layout {
  /**
   * Entities and relationships are absolute canvas coordinates; attributes are
   * offsets relative to their owner (SPEC.md §4).
   */
  positions: Record<Id, Position>;
}

export interface ErDocument {
  version: 1;
  title: string;
  model: ErModel;
  layout: Layout;
  /** Keys produced by `model/dismissals.ts`. */
  dismissedHints: string[];
}
